export const FETCH_BY_TIMELINE = 'FETCH_BY_TIMELINE';
export const FETCH_BY_TIMELINE_FAILED = 'FETCH_BY_TIMELINE_FAILED';

export const FETCH_NEWS = 'FETCH_NEWS';

export const FETCH_BY_COUNTRY = 'FETCH_BY_COUNTRY';
