export const FETCH_BY_TIMELINE_SUCCESS = 'FETCH_BY_TIMELINE_SUCCESS';
export const FETCH_BY_TIMELINE_START = 'FETCH_BY_TIMELINE_START';
export const FETCH_BY_TIMELINE_FAILED = 'FETCH_BY_TIMELINE_FAILED';

export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_START = 'FETCH_NEWS_START';

export const FETCH_BY_COUNTRY_SUCCESS = 'FETCH_BY_COUNTRY_SUCCESS';
export const FETCH_BY_COUNTRY_START = 'FETCH_BY_COUNTRY_START';
